name: example
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  fastmcp: ^0.1.6
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  fastmcp_generator: ^0.1.6
  lints: ^5.0.0
