name: fastmcp
description: A fast, declarative, and type-safe server framework for the Model Context Protocol (MCP)
version: 0.1.3
homepage: https://github.com/yashmakan/fastmcp
repository: https://github.com/yashmakan/fastmcp
issue_tracker: https://github.com/yashmakan/fastmcp/issues

environment:
  sdk: ^3.8.0

dependencies:
  uuid: ^4.5.1
  meta: '>=1.9.0 <2.0.0'
  logging: ^1.3.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
