name: fastmcp_generator
description: Code generator for the fastmcp framework. Annotate functions to automatically create MCP tools, resources, and prompts.
version: 0.1.5
homepage: https://github.com/yashmakan/fastmcp
repository: https://github.com/yashmakan/fastmcp
issue_tracker: https://github.com/yashmakan/fastmcp/issues

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.2.0
  fastmcp: ^0.1.5

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^5.0.0
  test: ^1.24.0
